apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "plantuml.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "plantuml.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.plantuml.ingress.annotations | indent 4 }}
spec:
 rules:
 - host: {{ .Values.plantuml.ingress.host }}
   http:
     paths:
     - path: /
       backend:
         serviceName: {{ include "plantuml.fullname" . }}
         servicePort: 80
